<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('properties')->insert([
            //For Sale
            [
                'user_id' => '1',
                'threesixty_link' => 'https://my.matterport.com/show/?m=BswfThZ38kh',
                'propert_title' => 'Demo Tile 1',
                'price' => '10000',
                'featured_photo' => 'property_featured_image/1623835677property.jpg',
                'bedroom' => '2',
                'bathroom' => '2',
                'garages' => '1',
                'area' => '1400',
                'property_type' => 'For Sale',
                'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
                'latitude' => '38.4177567',
                'longitude' => '-93.4343434',
                'zipcode' => '12131',
                'address' => 'San Francisco, CA 94112',
                'private_note' => 'This is private Note for Property',
                'created_at' => '2021-06-08 09:40:29'
            ],

            [
                'user_id' => '1',
                'threesixty_link' => '0',
                'propert_title' => 'Demo Tile 2',
                'price' => '10000',
                'featured_photo' => 'property_featured_image/1623835677property.jpg',
                'bedroom' => '3',
                'bathroom' => '3',
                'garages' => '1',
                'area' => '115000',
                'property_type' => 'For Sale',
                'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
                'latitude' => '38.187286',
                'longitude' => ' -92.773114',
                'zipcode' => '12131',
                'address' => 'San Francisco, CA 94112',
                'private_note' => 'This is private Note for Property',
                'created_at' => '2021-06-08 09:40:29'
            ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 3',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 4',
            //     'price' => '10000',
            //     'bedroom' => '2',
            //     'bathroom' => '2',
            //     'garages' => '1',
            //     'area' => '1400',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 5',
            //     'price' => '10000',
            //     'bedroom' => '3',
            //     'bathroom' => '3',
            //     'garages' => '1',
            //     'area' => '115000',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 6',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 7',
            //     'price' => '10000',
            //     'bedroom' => '2',
            //     'bathroom' => '2',
            //     'garages' => '1',
            //     'area' => '1400',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 8',
            //     'price' => '10000',
            //     'bedroom' => '3',
            //     'bathroom' => '3',
            //     'garages' => '1',
            //     'area' => '115000',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 9',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 10',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Sale',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // for rent


            [
                'user_id' => '4',
                'threesixty_link' => '0',
                'propert_title' => 'Demo Tile 1',
                'price' => '10000',
                'featured_photo' => 'property_featured_image/1623835677property.jpg',
                'bedroom' => '2',
                'bathroom' => '2',
                'garages' => '1',
                'area' => '1400',
                'property_type' => 'For Rent',
                'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
                'latitude' => '38.185454',
                'longitude' => '-92.765503',
                'zipcode' => '12131',
                'address' => 'San Francisco, CA 94112',
                'private_note' => 'This is private Note for Property',
                'created_at' => '2021-06-08 09:40:29'
            ],

            [
                'user_id' => '4',
                'threesixty_link' => '0',
                'propert_title' => 'Demo Tile 2',
                'price' => '10000',
                'featured_photo' => 'property_featured_image/1623835677property.jpg',
                'bedroom' => '3',
                'bathroom' => '3',
                'garages' => '1',
                'area' => '115000',
                'property_type' => 'For Rent',
                'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
                'latitude' => '38.188039',
                'longitude' => '-92.774794',
                'zipcode' => '12131',
                'address' => 'San Francisco, CA 94112',
                'private_note' => 'This is private Note for Property',
                'created_at' => '2021-06-08 09:40:29'

            ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 3',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 4',
            //     'price' => '10000',
            //     'bedroom' => '2',
            //     'bathroom' => '2',
            //     'garages' => '1',
            //     'area' => '1400',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 5',
            //     'price' => '10000',
            //     'bedroom' => '3',
            //     'bathroom' => '3',
            //     'garages' => '1',
            //     'area' => '115000',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 6',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 7',
            //     'price' => '10000',
            //     'bedroom' => '2',
            //     'bathroom' => '2',
            //     'garages' => '1',
            //     'area' => '1400',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 8',
            //     'price' => '10000',
            //     'bedroom' => '3',
            //     'bathroom' => '3',
            //     'garages' => '1',
            //     'area' => '115000',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 9',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 10',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Rent',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // for Investment

            [
                'user_id' => '4',
                'threesixty_link' => '0',
                'propert_title' => 'Demo Tile 1',
                'price' => '10000',
                'featured_photo' => 'property_featured_image/1623835677property.jpg',
                'bedroom' => '2',
                'bathroom' => '2',
                'garages' => '1',
                'area' => '1400',
                'property_type' => 'For Rent',
                'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
                'latitude' => '38.193709',
                'longitude' => '-92.757317',
                'zipcode' => '12131',
                'address' => 'San Francisco, CA 94112',
                'private_note' => 'This is private Note for Property',
                'created_at' => '2021-06-08 09:40:29'
            ],

            [
                'user_id' => '4',
                'threesixty_link' => '0',
                'propert_title' => 'Demo Tile 2',
                'price' => '10000',
                'featured_photo' => 'property_featured_image/1623835677property.jpg',
                'bedroom' => '3',
                'bathroom' => '3',
                'garages' => '1',
                'area' => '115000',
                'property_type' => 'For Sale',
                'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
                'latitude' => '38.196314',
                'longitude' => '-92.754420',
                'zipcode' => '12131',
                'address' => 'San Francisco, CA 94112',
                'private_note' => 'This is private Note for Property',
                'created_at' => '2021-06-08 09:40:29'
            ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 3',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 4',
            //     'price' => '10000',
            //     'bedroom' => '2',
            //     'bathroom' => '2',
            //     'garages' => '1',
            //     'area' => '1400',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 5',
            //     'price' => '10000',
            //     'bedroom' => '3',
            //     'bathroom' => '3',
            //     'garages' => '1',
            //     'area' => '115000',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 6',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 7',
            //     'price' => '10000',
            //     'bedroom' => '2',
            //     'bathroom' => '2',
            //     'garages' => '1',
            //     'area' => '1400',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 8',
            //     'price' => '10000',
            //     'bedroom' => '3',
            //     'bathroom' => '3',
            //     'garages' => '1',
            //     'area' => '115000',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 9',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],

            // [
            //     'user_id' => '3',
            //     'propert_title' => 'Demo Tile 10',
            //     'price' => '10000',
            //     'bedroom' => '5',
            //     'bathroom' => '3',
            //     'garages' => '3',
            //     'area' => '115000',
            //     'property_type' => 'For Investment',
            //     'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document.',
            //     'latitude' => '31.4177567',
            //     'longitude' => '13.4343434',
            //     'private_note' => 'This is private Note for Property',
            // ],
        ]);
    }
}
